



name: Deploy Vite React to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # `dist/` is the output folder from Vite React
          artifact_path: dist

      - name: Print deployed URL
        run: echo "✅ Your site is live at https://Ammara-Khalil.github.io/fashion/"